#!/usr/bin/env python3
"""
G-REG: product/registry.md is the rendered index of the manifest.

Two modes:
  python3 governance/check_registry.py              # gate mode: pass/fail
  python3 governance/check_registry.py --write      # regenerate registry.md

In gate mode, the sensor renders the registry in-memory from the current
manifest and compares to the on-disk file. Drift -> exit 1.

The registry is generated, never hand-edited. To update: change the manifest,
then run with --write.
"""

from __future__ import annotations

import collections
import json
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).parent.parent
MANIFEST = REPO_ROOT / "product" / "manifest"
CAPS_DIR = MANIFEST / "capabilities"
STORIES_DIR = MANIFEST / "stories"
FLOWS_DIR = MANIFEST / "flows"
REGISTRY = REPO_ROOT / "product" / "registry.md"
APP_SRC = REPO_ROOT / "app" / "src"

ANNOTATION_RE = re.compile(r"//\s*ac:\s*([A-Za-z0-9_-]+)")

WANT_MAX = 80
TITLE_MAX = 60


def truncate(s: str, n: int) -> str:
    s = s.replace("\n", " ").replace("|", "\\|").strip()
    if len(s) <= n:
        return s
    return s[: n - 1].rstrip() + "…"


def load_dir(d: pathlib.Path) -> dict[str, dict]:
    out: dict[str, dict] = {}
    if not d.exists():
        return out
    for f in sorted(d.glob("*.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        out[f.stem] = data
    return out


def collect_annotation_counts() -> collections.Counter:
    counts: collections.Counter = collections.Counter()
    if not APP_SRC.exists():
        return counts
    for kt in APP_SRC.rglob("*.kt"):
        text = kt.read_text(encoding="utf-8", errors="ignore")
        for m in ANNOTATION_RE.finditer(text):
            counts[m.group(1)] += 1
    return counts


def render(caps: dict, stories: dict, flows: dict, counts: collections.Counter) -> str:
    lines: list[str] = []
    lines.append("# Product Registry")
    lines.append("")
    lines.append(
        "> Generated by `python3 governance/check_registry.py --write`. "
        "Do not edit by hand."
    )
    lines.append("")
    lines.append(
        f"Totals: **{len(caps)}** capability/-ies, "
        f"**{len(stories)}** story/-ies, **{len(flows)}** flow(s)."
    )
    lines.append("")

    # ----- Capabilities -----
    lines.append("## Capabilities")
    lines.append("")
    lines.append("| ID | Title | Status | Stories | Flows |")
    lines.append("|----|-------|--------|---------|-------|")
    for cid in sorted(caps):
        c = caps[cid]
        title = truncate(c.get("title", ""), TITLE_MAX)
        status = c.get("status", "")
        story_ids = ", ".join(c.get("stories", []) or []) or "—"
        flow_ids = ", ".join(c.get("flows", []) or []) or "—"
        lines.append(f"| `{cid}` | {title} | {status} | {story_ids} | {flow_ids} |")
    lines.append("")

    # ----- Stories -----
    lines.append("## Stories")
    lines.append("")
    lines.append("| ID | Capability | Role | Want | ACs | Annotations |")
    lines.append("|----|------------|------|------|-----|-------------|")
    for sid in sorted(stories):
        s = stories[sid]
        cap = s.get("capability", "")
        role = s.get("role", "")
        want = truncate(s.get("want", ""), WANT_MAX)
        ac_count = len(s.get("acceptance") or [])
        anns = counts.get(sid, 0)
        cov = f"{anns}/{ac_count}"
        lines.append(
            f"| `{sid}` | `{cap}` | {role} | {want} | {ac_count} | {cov} |"
        )
    lines.append("")

    # ----- Flows -----
    lines.append("## Flows")
    lines.append("")
    lines.append("| ID | Steps | App steps | Stories referenced |")
    lines.append("|----|-------|-----------|--------------------|")
    for fid in sorted(flows):
        f = flows[fid]
        steps = f.get("steps") or []
        app_steps = sum(1 for s in steps if s.get("actor") == "app")
        refs = sorted({s.get("story") for s in steps if s.get("story")})
        ref_str = ", ".join(refs) if refs else "—"
        lines.append(f"| `{fid}` | {len(steps)} | {app_steps} | {ref_str} |")
    lines.append("")

    # ----- Source mapping -----
    lines.append("## Story → source coverage")
    lines.append("")
    lines.append(
        "Number of `// ac: <story-id>` annotations found across `app/src/**.kt`. "
        "Each story needs at least one per acceptance line (enforced by G31)."
    )
    lines.append("")
    lines.append("| Story | feature folder (expected) | AC coverage |")
    lines.append("|-------|---------------------------|-------------|")
    for sid in sorted(stories):
        s = stories[sid]
        cap = s.get("capability", "")
        feature = cap.replace("-", "_") if cap else ""
        ac_count = len(s.get("acceptance") or [])
        anns = counts.get(sid, 0)
        status = "OK" if anns >= ac_count else f"missing {ac_count - anns}"
        lines.append(
            f"| `{sid}` | `{feature}` | {anns}/{ac_count} ({status}) |"
        )
    lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    write_mode = "--write" in argv

    caps = load_dir(CAPS_DIR)
    stories = load_dir(STORIES_DIR)
    flows = load_dir(FLOWS_DIR)
    counts = collect_annotation_counts()

    rendered = render(caps, stories, flows, counts)

    if write_mode:
        REGISTRY.parent.mkdir(parents=True, exist_ok=True)
        REGISTRY.write_text(rendered, encoding="utf-8")
        print(f"Wrote {REGISTRY.relative_to(REPO_ROOT)} "
              f"({len(caps)} cap, {len(stories)} story, {len(flows)} flow)")
        return 0

    if not REGISTRY.exists():
        print("G-REG FAIL: product/registry.md does not exist.")
        print("  Fix: python3 governance/check_registry.py --write")
        return 1

    on_disk = REGISTRY.read_text(encoding="utf-8")
    if on_disk != rendered:
        # Identify the first differing line to help the developer.
        a = on_disk.splitlines()
        b = rendered.splitlines()
        diff_line = -1
        for i in range(min(len(a), len(b))):
            if a[i] != b[i]:
                diff_line = i + 1
                break
        if diff_line == -1 and len(a) != len(b):
            diff_line = min(len(a), len(b)) + 1

        print("G-REG FAIL: product/registry.md is out of sync with manifest.")
        if diff_line > 0:
            print(f"  First divergence around line {diff_line}.")
        print("  Fix: python3 governance/check_registry.py --write")
        return 1

    print(
        f"G-REG PASS: registry matches manifest "
        f"({len(caps)} cap, {len(stories)} story, {len(flows)} flow)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
